SOCIAL_MEDIA_DOMAINS = {
    "YouTube": [
        "youtube.com",
        "ytimg.com",
        "googlevideo.com",
        "yt3.ggpht.com",
        "youtubei.googleapis.com",
        "youtube-ui.l.google.com",
        "youtube.googleapis.com",
    ],
    "Facebook": [
        "facebook.com",
        "fbcdn.net",
        "facebook.net",
        "fbsbx.com",
        "fbpigeon.com",
        "fb.com",
        "facebook-hardware.com",
    ],
    "Pinterest": [
        "pinterest.com",
        "pinimg.com",
        "cdx.cedexis.net",
        "pinterest.net",
        "pinterest.pt",
        "pinterest.cl",
        "pinterest.info",
    ],
    "Instagram": [
        "instagram.com",
        "cdninstagram.com",
        "z-p42-chat-e2ee-ig.facebook.com",
        "mqtt-ig-p4.facebook.com",
        "z-p42-chat-e2ee-ig-fallback.facebook.com",
        "ig.me",
        "instagram.am",
        "igsonar.com",
    ],
    "Telegram": ["telegram.org", "t.me", "telegram.me", "tg.dev", "telesco.pe"],
    "WhatsApp": [
        "whatsapp.net",
        "whatsapp.com",
        "wa.me",
        "wl.co",
        "whatsappbrand.com",
        "whatsapp-plus.info",
        "whatsapp-plus.me",
        "whatsapp-plus.net",
        "whatsapp.cc",
        "whatsapp.info",
        "whatsapp.org",
        "whatsapp.tv",
    ],
    "Twitter/X": [
        "twitter.com",
        "t.co",
        "anuncios-twitter.com",
        "twimg.com",
        "x.com",
        "pscp.tv",
        "twtrdns.net",
        "twttr.com",
        "periscopio.tv",
        "twitpic.com",
        "tweetdeck.com",
        "twitter.co",
        "twitterinc.com",
        "twitteroauth.com",
        "twitterstat.us",
    ],
}
